In [ ]:
import numpy as np
import sys

# Basics

In [17]:
# Create array
a = np.array([1,2,3]) # integers
print(a)

c = np.array([1,2,3], dtype='int16') # less space

[1 2 3]


In [10]:
# Create 2-dimensional arrays
b = np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]]) # floats
print(b)

[[4. 5. 6.]
 [7. 8. 9.]]


In [13]:
# Get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [15]:
# Get shapes (rows, columns)
print(a.shape) 
print(b.shape)

(3,)
(2, 3)


In [18]:
# Get datatype
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
float64
int16


# Accessing and Changing specific elements, rows, columns

In [36]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

# Index with [row, column]
print(a[0,0])
print(a[1,-1])

# Get a specific row
print(a[1, :])

# Get a specific column
print(a[:,2])

# [startIndex:endIndex:stepSize]
print(a[0,1:4:2])

# Change
print("--------------------")
print(a)
a[1,-1] = 20
print("--------------------")
print(a)
print("--------------------")
a[0,:] = 5
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
10
[ 6  7  8  9 10]
[3 8]
[2 4]
--------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
--------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 20]]
--------------------
[[ 5  5  5  5  5]
 [ 6  7  8  9 20]]


In [41]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

# Get specific element (work outside in)
print(b[0,1,1]) # 1st set, 2nd row, 2nd column
print(b[:,1,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[3 4]
 [7 8]]


# Creating matrices 

In [54]:
# All 0s matrix
print(np.zeros(5)) # 5 zero elements
print("-------------")
print(np.zeros((2,3))) # 2 rows, 3 columns
print("-------------")

# All 1s matrix
print(np.ones((4,2,2), dtype='int32')) # 4 sets, 2 rows, 2 columns
print("-------------")


# For other numbers than 0s and 1s:
print(np.full((2,2), 10, dtype='float32'))
print("-------------")

# For other numbers than 0s and 1s:
print(np.full(a.shape,4))
print("-------------")
print(np.full_like(a, 4))

[0. 0. 0. 0. 0.]
-------------
[[0. 0. 0.]
 [0. 0. 0.]]
-------------
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
-------------
[[10. 10.]
 [10. 10.]]
-------------
[[4 4 4 4 4]
 [4 4 4 4 4]]
-------------
[[4 4 4 4 4]
 [4 4 4 4 4]]


In [62]:
# Random decimal numbers
print(np.random.rand(2,3,4))

# Random integer values (min val, max val, size =)
print(np.random.randint(10, size = (3,3)))
print(np.random.randint(1,5, size = (3,3)))

[[[0.37863859 0.04112845 0.32327855 0.6477411 ]
  [0.30111893 0.48830847 0.36950232 0.28244325]
  [0.12763859 0.86335278 0.62535833 0.45248424]]

 [[0.13408861 0.39424642 0.99120915 0.78030932]
  [0.59468111 0.59505991 0.10983454 0.73549702]
  [0.42858161 0.86293851 0.01290007 0.6316852 ]]]
[[5 5 9]
 [1 0 5]
 [5 4 2]]
[[4 3 4]
 [1 2 1]
 [1 4 1]]


# Mathematics

In [67]:
a = np.array([1,2,3,4,5])
print(a)

print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[1 2 3 4 5]
[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [69]:
b = np.array([6,7,8,9,10])
a + b

array([ 7,  9, 11, 13, 15])